### ISSUE TITLE
ui-bootstrap-tpls library must be included from 7.5

### ISSUE THREAD

**Issue by goenkale** [Bonitasoft-Community/widget_autocompletekey#2]
[ui-bootstrap-tpls-0.13.0.min.js.txt](https://github.com/Bonitasoft-Community/widget_autocompletekey/files/1248740/ui-bootstrap-tpls-0.13.0.min.js.txt)

Remove the .txt extension and add this file as a JS asset into your custom widget.

**Comment by pierre-yves-monnet** [comment]
Done
